
import AddBootstrap from "./components/BootstrapClient";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Bricolage_Grotesque } from "next/font/google";


const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={bricolage.className}>
        <AddBootstrap/>
        {children}
      </body>
    </html>
  );
}
